### ISSUE TITLE
Pretrained weights

### ISSUE THREAD

**Issue by shiron8bit** [bit-ml/dolos#1]
Hey, great work, 
any chances you will publish the pretrained weights?

**Comment by danoneata** [comment]
Hello! Thank you for the interest in our work. We have uploaded [here](https://sharing.speed.pub.ro/owncloud/index.php/s/MTSTY7tnKqn21h4) the Patches models corresponding to our experiments in sections 5.1 and 5.2. Let us know if these suffice. You can download them as follows:
```bash
cd path/to/dolos
wget https://sharing.speed.pub.ro/owncloud/index.php/s/MTSTY7tnKqn21h4/download -O dolos-models-patches.zip
unzip dolos-models-patches.zip
```
